travis:
  secure:
    BINSTAR_TOKEN: CrNATrV+iHhZMsaJaKfHf8idj/7SVXJgY4rTUmPY1L4oEQPfnTeGG718Siba2CiM56aYw8VLHdTDp/Sw5kAkLntvc5OD/APrZl5ws0fn6GLyZdo7VaGubfvzAqRiLdnebeVniOE+rIe/irFaFhoLclLOkKqZtXyaojyNt1KuDskmH14yDfsJXWzHALthJkWgKP7Oqiv8syOFoK5YFBrnX+fEfFvQh0sYw/UNpKoaiaFVmdI0oWm1PbpeIaFShBZD1E2x989bZT3sUJDwzDCou8n5mYNuFcf5dGT8oJAp6uKgXp8QowtyEWf9Os5wmiZZCI5vxZfw0YjiM+wkrggCKjzgW05eeK7Jr6TGAhsG7eCaVlhc722MUEPeCEVk4jHQREFPMeULa45VNzihgGf6imqGoB7ud4cG/jUvvpOKnaYLa2pBCz+OosPaneAMhar8uXmJ9ZoE39CEmMuTKUtlg73wukkV3ObSax40w4HD8kIt7WRI5ZfzRz6m7enAq25Jbxjbsk5CtLf/1u0vGE59xTUndhaIgQlc9DSt/HVl0qJlhGdybEh4z0N1BFW8h6t5XHNVHmh1pMX6vtGBj/04gr99JfwcqF+IjCiIQywDomD4Ma6cyq9NPYhcLl43ba7bw1mW/QfLx3JURmtkj2ZxTMcIneurNJ62LRT+JFr54pE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
